# SPDX-FileCopyrightText: Lada Authors
# SPDX-License-Identifier: AGPL-3.0

from __future__ import annotations

import json
import os
import pathlib
import shutil
from dataclasses import dataclass
from time import perf_counter
from typing import Any

from lada import VERSION
from lada.restorationpipeline.frame_restorer import FrameRestorer
from lada.restorationpipeline.model_loader import LoadedModels
from lada.restorationpipeline.runtime_profiling import WallClockProfiler
from lada.utils import audio_utils, video_utils
from lada.utils.threading_utils import ErrorMarker, STOP_MARKER
from lada.utils.video_utils import VideoWriter, get_video_meta_data

from . import utils

_OUTPUT_PIPELINE_REVISION_ENV = "LADA_OUTPUT_PIPELINE_REVISION"


@dataclass(frozen=True)
class VideoProcessingRequest:
    """Arguments required to process one video through the restoration pipeline."""

    input_path: str
    output_path: str
    temp_dir_path: str
    loaded_models: LoadedModels
    mosaic_restoration_model_name: str
    max_clip_length: int
    encoder: str
    encoder_options: str
    mp4_fast_start: bool
    working_output_path: str | None = None
    output_metadata: dict[str, object] | None = None


def compute_target_to_report(compute_target: Any) -> dict[str, object]:
    """Serialize one resolved compute target into the CLI timing report."""

    return {
        "id": compute_target.id,
        "description": compute_target.description,
        "runtime": compute_target.runtime,
        "available": compute_target.available,
        "torch_device": compute_target.torch_device,
        "notes": compute_target.notes,
        "experimental": compute_target.experimental,
    }


def write_timing_report(report_path: str, report: dict[str, object]) -> None:
    """Write one CLI timing report to disk."""

    pathlib.Path(report_path).parent.mkdir(exist_ok=True, parents=True)
    with open(report_path, "w", encoding="utf-8") as file_obj:
        json.dump(report, file_obj, indent=2, ensure_ascii=False)


def build_output_metadata(
    *,
    device_id: str,
    mosaic_restoration_model_name: str,
    mosaic_detection_model_name: str,
    encoder: str,
) -> dict[str, str]:
    """Build the metadata block embedded into output media files."""

    pipeline_revision = _get_output_pipeline_revision() or "unspecified"
    return {
        "title": "Lada restored video",
        "comment": f"lada_version={VERSION}; pipeline_revision={pipeline_revision}",
        "description": (
            f"Generated by Lada {VERSION}; device={device_id}; "
            f"restoration_model={mosaic_restoration_model_name}; "
            f"detection_model={mosaic_detection_model_name}; encoder={encoder}"
        ),
        "software": f"Lada {VERSION}",
    }


def process_video_file(request: VideoProcessingRequest) -> dict[str, object]:
    """Restore one input video and return a structured execution report."""

    profiler = WallClockProfiler()
    started_at = perf_counter()
    encoded_output_path = request.working_output_path or request.output_path
    normalized_output_metadata = video_utils.normalize_output_metadata(
        request.output_metadata,
    )
    with profiler.measure("video_metadata_probe_s"):
        video_metadata = get_video_meta_data(request.input_path)

    with profiler.measure("frame_restorer_init_s"):
        frame_restorer = FrameRestorer(
            request.loaded_models.frame_device,
            request.input_path,
            request.max_clip_length,
            request.mosaic_restoration_model_name,
            request.loaded_models.detection_model,
            request.loaded_models.restoration_model,
            request.loaded_models.preferred_pad_mode,
        )
    success = True
    frames_written = 0
    audio_profile: dict[str, object] = {}
    frame_restorer_profile: dict[str, object] = {}
    video_writer: VideoWriter | None = None
    error_message: str | None = None
    video_tmp_file_output_path = video_utils.build_temp_video_output_path(
        request.temp_dir_path,
        encoded_output_path,
    )
    pathlib.Path(request.output_path).parent.mkdir(exist_ok=True, parents=True)
    if request.working_output_path:
        pathlib.Path(encoded_output_path).parent.mkdir(exist_ok=True, parents=True)
    frame_restorer_progressbar = utils.Progressbar(video_metadata)
    try:
        with profiler.measure("frame_restorer_start_s"):
            frame_restorer.start()
        frame_restorer_progressbar.init()
        with profiler.measure("video_writer_open_s"):
            video_writer = VideoWriter(
                video_tmp_file_output_path,
                video_metadata.video_width,
                video_metadata.video_height,
                video_metadata.video_fps_exact,
                encoder=request.encoder,
                encoder_options=request.encoder_options,
                time_base=video_metadata.time_base,
                mp4_fast_start=request.mp4_fast_start,
                metadata=normalized_output_metadata,
            )
        with profiler.measure("restore_write_loop_s"):
            frame_restorer_iterator = iter(frame_restorer)
            while True:
                with profiler.measure("frame_restorer_next_s"):
                    try:
                        elem = next(frame_restorer_iterator)
                    except StopIteration:
                        break
                if elem is STOP_MARKER or isinstance(elem, ErrorMarker):
                    success = False
                    frame_restorer_progressbar.error = True
                    if isinstance(elem, ErrorMarker):
                        raise RuntimeError(
                            f"Frame restoration pipeline failed: {elem}\n"
                            f"{elem.stack_trace}"
                        )
                    raise RuntimeError(
                        "Frame restoration pipeline stopped prematurely.",
                    )
                restored_frame, restored_frame_pts = elem
                with profiler.measure("video_writer_write_s"):
                    video_writer.write(restored_frame, restored_frame_pts, bgr2rgb=True)
                frames_written += 1
                frame_restorer_progressbar.update()
    except (Exception, KeyboardInterrupt) as exc:
        success = False
        if isinstance(exc, KeyboardInterrupt):
            raise
        error_message = str(exc)
        print("Error on export", exc)
    finally:
        if video_writer is not None:
            try:
                with profiler.measure("video_writer_release_s"):
                    video_writer.release()
            except Exception as exc:
                success = False
                error_message = str(exc)
                print("Error on export", exc)
        with profiler.measure("frame_restorer_stop_s"):
            frame_restorer.stop()
        frame_restorer_profile = frame_restorer.get_last_profile()
        frame_restorer_progressbar.close(ensure_completed_bar=success)

    if success:
        if _is_full_video_passthrough(frame_restorer_profile):
            print(_("No mosaic clips detected, preserving original video"))
            with profiler.measure("output_passthrough_total_s"):
                input_extension = os.path.splitext(request.input_path)[1].lower()
                output_extension = os.path.splitext(request.output_path)[1].lower()
                input_audio_codec = audio_utils.get_audio_codec(
                    video_metadata.video_file,
                )
                # If the final output keeps the original suffix, preserve the source
                # bytes directly. Batch workflows rely on this when they deliberately
                # keep non-default container extensions.
                can_copy_original = input_extension == output_extension
                passthrough_reason = (
                    "matching_extension_direct_copy" if can_copy_original else None
                )
                if not can_copy_original:
                    can_copy_original, passthrough_reason = (
                        audio_utils.can_copy_video_file_to_output(
                            video_metadata.codec_name,
                            input_audio_codec,
                            request.output_path,
                        )
                    )
                if can_copy_original:
                    audio_profile = audio_utils.copy_or_remux_video_file(
                        request.input_path,
                        request.output_path,
                        metadata=normalized_output_metadata,
                    )
                    audio_profile["passthrough_original_video"] = True
                    audio_profile["passthrough_reason"] = passthrough_reason
                    _cleanup_intermediate_outputs(
                        video_tmp_file_output_path=video_tmp_file_output_path,
                        working_output_path=encoded_output_path,
                        output_path=request.output_path,
                    )
                else:
                    print(
                        _(
                            "Preserving original video skipped, falling back to encoded passthrough",
                        ),
                        passthrough_reason,
                    )
                    audio_profile = audio_utils.combine_audio_video_files(
                        video_metadata,
                        video_tmp_file_output_path,
                        encoded_output_path,
                        metadata=normalized_output_metadata,
                    )
                    audio_profile["passthrough_original_video"] = False
                    audio_profile["passthrough_fallback"] = "encoded_passthrough"
                    audio_profile["passthrough_reason"] = passthrough_reason
        else:
            print(_("Processing audio"))
            with profiler.measure("audio_mux_total_s"):
                audio_profile = audio_utils.combine_audio_video_files(
                    video_metadata,
                    video_tmp_file_output_path,
                    encoded_output_path,
                    metadata=normalized_output_metadata,
                )
        if encoded_output_path != request.output_path and os.path.exists(
            encoded_output_path,
        ):
            encoded_output_extension = os.path.splitext(encoded_output_path)[1].lower()
            final_output_extension = os.path.splitext(request.output_path)[1].lower()
            if encoded_output_extension != final_output_extension:
                raise RuntimeError(
                    "Refusing to rename a staged output with a different container "
                    f"extension: '{encoded_output_path}' -> '{request.output_path}'",
                )
            if os.path.exists(request.output_path):
                os.remove(request.output_path)
            shutil.move(encoded_output_path, request.output_path)
    else:
        _cleanup_intermediate_outputs(
            video_tmp_file_output_path=video_tmp_file_output_path,
            working_output_path=encoded_output_path,
            output_path=request.output_path,
        )

    report: dict[str, object] = {
        "input_path": request.input_path,
        "output_path": request.output_path,
        "success": success,
        "frames_written": frames_written,
        "video_metadata": _video_metadata_to_report(video_metadata),
        "stages": profiler.snapshot(total_s=perf_counter() - started_at),
        "frame_restorer": frame_restorer_profile,
        "audio_mux": audio_profile,
        "passthrough_original_video": bool(
            audio_profile.get("passthrough_original_video"),
        ),
        "output_exists": os.path.exists(request.output_path),
        "working_output_path": (
            encoded_output_path if encoded_output_path != request.output_path else None
        ),
        "output_metadata": normalized_output_metadata,
        "error_message": error_message,
    }
    if os.path.exists(request.output_path):
        report["output_size_bytes"] = os.path.getsize(request.output_path)
    return report


def _video_metadata_to_report(video_metadata: Any) -> dict[str, object]:
    return {
        "video_file": video_metadata.video_file,
        "video_width": video_metadata.video_width,
        "video_height": video_metadata.video_height,
        "video_fps": float(video_metadata.video_fps),
        "video_fps_exact": str(video_metadata.video_fps_exact),
        "frames_count": video_metadata.frames_count,
        "duration": float(video_metadata.duration),
        "time_base": str(video_metadata.time_base),
        "start_pts": video_metadata.start_pts,
        "codec_name": video_metadata.codec_name,
    }


def _get_output_pipeline_revision() -> str | None:
    pipeline_revision = os.environ.get(_OUTPUT_PIPELINE_REVISION_ENV, "").strip()
    return pipeline_revision or None


def _is_full_video_passthrough(frame_restorer_profile: dict[str, object]) -> bool:
    mosaic_detector_profile = frame_restorer_profile.get("mosaic_detector")
    if not isinstance(mosaic_detector_profile, dict):
        return False
    return (
        int(frame_restorer_profile.get("clips_restored", 0)) == 0
        and int(frame_restorer_profile.get("frames_blended", 0)) == 0
        and int(mosaic_detector_profile.get("clips_emitted", 0)) == 0
    )


def _cleanup_intermediate_outputs(
    *,
    video_tmp_file_output_path: str,
    working_output_path: str | None,
    output_path: str,
) -> None:
    if os.path.exists(video_tmp_file_output_path):
        os.remove(video_tmp_file_output_path)
    if (
        working_output_path
        and os.path.exists(working_output_path)
        and os.path.normcase(working_output_path) != os.path.normcase(output_path)
    ):
        os.remove(working_output_path)
